Error fetching data from http://65.109.79.117:8080/v1: HTTPConnectionPool(host='65.109.79.117', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8fae99a8f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://65.109.25.102:8080/v1: HTTPConnectionPool(host='65.109.25.102', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8fae99acb0>, 'Connection to 65.109.25.102 timed out. (connect timeout=5)'))
Error fetching data from http://65.109.106.116:8080/v1: HTTPConnectionPool(host='65.109.106.116', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8fae99b7c0>, 'Connection to 65.109.106.116 timed out. (connect timeout=5)'))
Error fetching data from http://136.244.71.63:8080/v1: HTTPConnectionPool(host='136.244.71.63', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8fae99bf10>, 'Connection to 136.244.71.63 timed out. (connect timeout=5)'))
Error fetching data from http://99.145.200.98:8080/v1: HTTPConnectionPool(host='99.145.200.98', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8fae99b2e0>, 'Connection to 99.145.200.98 timed out. (connect timeout=5)'))
{'http://188.40.107.105:8080/v1': 3904673, 'http://70.15.242.6:8080/v1': 3874614}
Nginx configuration updated!
