Error fetching data from http://204.186.74.42:8080/v1: HTTPConnectionPool(host='204.186.74.42', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefc94862c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error fetching data from http://51.159.101.31:8080/v1: HTTPConnectionPool(host='51.159.101.31', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefc9486c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://65.109.159.23:8080/v1': 622902, 'http://5.9.73.119:8080/v1': 622904, 'http://188.40.107.105:8080/v1': 616107, 'http://212.227.188.13:8080/v1': 622906, 'http://5.161.128.117:8080/v1': 622906, 'http://136.244.71.63:8080/v1': 622906, 'http://136.243.93.42:8080/v1': 622912}
Nginx configuration updated!
