Error fetching data from http://65.109.80.179:8080/v1: HTTPConnectionPool(host='65.109.80.179', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2eadfec760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://209.38.172.53:8080/v1: HTTPConnectionPool(host='209.38.172.53', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2eadfed030>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://35.83.165.32:8080/v1: HTTPConnectionPool(host='35.83.165.32', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2eadfec670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://172.86.64.60:8080/v1: HTTPConnectionPool(host='172.86.64.60', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2eadfed120>, 'Connection to 172.86.64.60 timed out. (connect timeout=5)'))
Error fetching data from http://202.182.97.107:8080/v1: HTTPConnectionPool(host='202.182.97.107', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2eadfeded0>, 'Connection to 202.182.97.107 timed out. (connect timeout=5)'))
Error fetching data from http://45.61.132.146:8080/v1: HTTPConnectionPool(host='45.61.132.146', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2eadfed090>, 'Connection to 45.61.132.146 timed out. (connect timeout=5)'))
Error fetching data from http://167.88.160.51:8080/v1: HTTPConnectionPool(host='167.88.160.51', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2eadfec700>, 'Connection to 167.88.160.51 timed out. (connect timeout=5)'))
Error fetching data from http://70.15.242.6:8080/v1: HTTPConnectionPool(host='70.15.242.6', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2eadfee2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://222.101.31.242:8080/v1': 46736976, 'http://172.104.211.8:8080/v1': 46736948, 'http://38.242.137.192:8080/v1': 46736978, 'http://160.202.129.29:8080/v1': 46736962, 'http://65.109.30.57:8080/v1': 46736888, 'http://vfn.0l.kalvkusk.io:8080/v1': 46736964, 'http://84.247.189.19:8080/v1': 46736958, 'http://37.27.83.253:8080/v1': 46737058}
Nginx configuration updated!
