Error fetching data from http://172.86.64.60:8080/v1: HTTPConnectionPool(host='172.86.64.60', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1be7fe8a30>, 'Connection to 172.86.64.60 timed out. (connect timeout=5)'))
Error fetching data from http://202.182.97.107:8080/v1: HTTPConnectionPool(host='202.182.97.107', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1be7fe8ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://45.61.132.146:8080/v1: HTTPConnectionPool(host='45.61.132.146', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1be7fe9630>, 'Connection to 45.61.132.146 timed out. (connect timeout=5)'))
Error fetching data from http://167.88.160.51:8080/v1: HTTPConnectionPool(host='167.88.160.51', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1be7fe9d80>, 'Connection to 167.88.160.51 timed out. (connect timeout=5)'))
{'http://222.101.31.242:8080/v1': 31332645, 'http://65.109.80.179:8080/v1': 31332645, 'http://172.104.211.8:8080/v1': 31332647, 'http://38.242.137.192:8080/v1': 31332647, 'http://160.202.129.29:8080/v1': 31332649, 'http://209.38.172.53:8080/v1': 31332647, 'http://65.109.30.57:8080/v1': 31332617, 'http://vfn.0l.kalvkusk.io:8080/v1': 31332651, 'http://35.83.165.32:8080/v1': 31332643, 'http://84.247.189.19:8080/v1': 31332657, 'http://37.27.83.253:8080/v1': 31332709, 'http://70.15.242.6:8080/v1': 31332713}
Nginx configuration updated!
