Error fetching data from http://88.198.51.250:8080/v1: HTTPConnectionPool(host='88.198.51.250', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f55bc27a380>, 'Connection to 88.198.51.250 timed out. (connect timeout=5)'))
Error fetching data from http://73.181.115.53:8080/v1: HTTPConnectionPool(host='73.181.115.53', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55bc27ab00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://70.15.242.6:8080/v1: HTTPConnectionPool(host='70.15.242.6', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55bc27b250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://65.108.233.71:8080/v1: HTTPConnectionPool(host='65.108.233.71', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f55bc27bf10>, 'Connection to 65.108.233.71 timed out. (connect timeout=5)'))
Error fetching data from http://51.159.100.217:8080/v1: HTTPConnectionPool(host='51.159.100.217', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55bc27bbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://222.101.31.242:8080/v1: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Error fetching data from http://158.220.123.33:8080/v1: HTTPConnectionPool(host='158.220.123.33', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55bc278b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://50.29.171.32:8080/v1: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Error fetching data from http://94.130.22.86:8080/v1: HTTPConnectionPool(host='94.130.22.86', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55bc048e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://65.109.80.179:8080/v1': 2471144, 'http://65.108.230.116:8080/v1': 2471144, 'http://65.108.15.240:8080/v1': 2471144, 'http://172.104.211.8:8080/v1': 2471144, 'http://142.132.217.22:8080/v1': 2471144}
Nginx configuration updated!
