Error fetching data from http://135.181.118.28:8080: HTTPConnectionPool(host='135.181.118.28', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54358f2a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data from http://142.132.207.31:8080: HTTPConnectionPool(host='142.132.207.31', port=8080): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f54358f2f20>, 'Connection to 142.132.207.31 timed out. (connect timeout=5)'))
Error fetching data from http://5.161.130.81:8080: HTTPConnectionPool(host='5.161.130.81', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54358f3670>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://104.248.94.195:8080': 140158915, 'http://136.243.59.175:8080': 138346714, 'http://144.76.104.93:8080': 140158932, 'http://63.229.234.76:8080': 140158932, 'http://63.229.234.77:8080': 140158932, 'http://65.108.14.25:8080': 140158933, 'http://65.108.233.71:8080': 140158933, 'http://88.198.51.250:8080': 140158933, 'http://94.130.22.86:8080': 140158933}
Nginx configuration updated!
