Error fetching data from http://45.61.132.146:8080/v1: HTTPConnectionPool(host='45.61.132.146', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b4c2d8280>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://222.101.31.242:8080/v1': 13030677, 'http://65.109.80.179:8080/v1': 13030677, 'http://172.104.211.8:8080/v1': 13030679, 'http://38.242.137.192:8080/v1': 13030681, 'http://160.202.129.29:8080/v1': 13030681, 'http://209.38.172.53:8080/v1': 13030681, 'http://65.109.30.57:8080/v1': 13030683, 'http://vfn.0l.kalvkusk.io:8080/v1': 13030683, 'http://35.83.165.32:8080/v1': 13030685, 'http://84.247.189.19:8080/v1': 13030687, 'http://172.86.64.60:8080/v1': 13030687, 'http://202.182.97.107:8080/v1': 13030687, 'http://167.88.160.51:8080/v1': 13030689, 'http://70.15.242.6:8080/v1': 13030689}
Nginx configuration updated!
